name: Wake Up Codespace
on:
  repository_dispatch:
    types: [start-server]

permissions: write-all

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Codespace
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CS_NAME=$(gh codespace list --repo 80softer/SushiSMP --json name -q '.[0].name')
          if [ -z "$CS_NAME" ]; then
            echo "❌ Codespaceが見つかりませんでした。"
            exit 1
          fi
          gh codespace code -c "$CS_NAME"
          echo "✅ 起動命令を送信しました！"
